version: "3.9"

services:
  auth-service:
    build:
      context: ..
      dockerfile: docker/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"

  sales-service:
    build:
      context: ..
      dockerfile: docker/sales-service/Dockerfile
    container_name: sales-service
    ports:
      - "8000:8000"
    volumes:
      - ../sales-system/backend/data:/app/data

  ui:
    build:
      context: ..
      dockerfile: docker/ui/Dockerfile
    container_name: sales-ui
    ports:
      - "8501:8501"
    volumes:
      - ../sales-system/backend/data:/app/data
    depends_on:
      - auth-service
      - sales-service
